### ISSUE TITLE
S variant differences / to-do list

### ISSUE THREAD

**Issue by suprstarrd** [ac-music-extension-s/ac-music-extension-s#11]
## To-do list
- [ ] https://github.com/animal-crossing-music-extension/ac-music-extension/pull/165
- [ ] #15 
- [ ] #25
- [ ] #13 
- [ ] #16
- [ ] #20 
- [ ] #21
- [ ] #24
- [ ] https://github.com/animal-crossing-music-extension/ac-music-extension/issues/152
- [ ] https://github.com/animal-crossing-music-extension/ac-music-extension/issues/134
- [ ] https://github.com/animal-crossing-music-extension/ac-music-extension/issues/95
- [ ] https://github.com/animal-crossing-music-extension/ac-music-extension/issues/61
- [ ] https://github.com/animal-crossing-music-extension/ac-music-extension/issues/67
- [ ] #12 
- [x] https://github.com/animal-crossing-music-extension/ac-music-extension/issues/78
- [x] While using live weather, don't restart the song if the current weather is the same as the song already playing
- [x] #17
- [x] https://github.com/animal-crossing-music-extension/ac-music-extension/issues/144
   - [x] When the weather changes while an hourly song is playing, the song should smoothly transition between variants instead of abruptly cutting out and restarting
   - [x] When using both "Live Weather" and "Random", a change in the weather should not change which game's music is currently being played
- [ ] Merge parts of T4 variant (also see https://github.com/SilverT4/ac-mus-ext-t4/issues/1)
   - [ ] Add support for WeatherAPI.com as a weather provider
   - [ ] Add support for user favorites per hour

## Merged from upstream
- https://github.com/animal-crossing-music-extension/ac-music-extension/pull/86 (`feat/eslinter` - will continue to work on!)
- https://github.com/animal-crossing-music-extension/ac-music-extension/pull/125 (`enhancement/css`)
- `Minor-patching` branch

**Comment by suprstarrd** [comment]
T4 variant to-do list:
> * [ ] Add a section to the options page for favourite game tracks by hour/weather
>     * [ ] Add associated handlers in the background scripts (Likely should be done first)
> * [x] Add weatherAPI as a weather provider. I'm a bit more familiar with it than the [base extension](https://github.com/animal-crossing-music-extension/ac-music-extension)'s API, considering said API isn't open source.
>     * ~~Still have a few issues to work out.~~ Never mind, I was a little silly and forgot the callback ;w;
> * [ ] Add a system for saving town tune presets
>     * [ ] Add associated HTML in options2, likely a fieldset next to the controls.
>     * [ ] Add JS code in either tune_editor.js or a new file altogether.
>         * Might go for the latter.
